tickers:
  - AAPL
  - MSFT
  - GOOG
  - AMZN
  - TSLA
  - FB
  - NVDA
  - TSM
  - TCEHY
  - BABA
  - ASML
  - AVGO
  - CSCO
  - ORCL
  - ADBE
  - CRM
  - INTC
  - AMD
  - TXN
  - NFLX
  - QCOM
  - INTU
  - SAP
  - IBM
  - TEAM
  - ADP
  - SPY
  - VOOG
  - SQ
  - ARKK